### ISSUE TITLE
Skalierung der Bücher-Container wäre wünschenswert

### ISSUE THREAD

**Issue by qwrtzp** [DSIW/sdf#100]
Mit manchen Auflösungen (1280×600  980×1280) sehen die Bücher-Listen nicht so schick aus. Zu viel weißer Rand rechts und eigentlich sind die Bücher auch zu groß, man muss dann sehr viel scrollen. Hier wäre es eigentlich schön, wenn die Größe der Bücher sich an die Auflösung anpasst.

![](http://i.imgur.com/2GQIyNP.png)

**Comment by CDanU** [comment]
Das mit den Rändern ist im uiImprovments branch eigentlich schon gelöst, jedoch noch nicht ganz perfekt. Die Skalierung wird etwas problematisch. Mit einer 320 x 480px Auflösung verbraucht gerade ein Buch in der Höhe mehr als einen ganzen Bildschirm. Das Cover zu skalieren ist eigentl. kein Problem, die Fonts können wir jedoch nicht prozentual Skalieren, sie sollten immer mind. 10px groß bleiben. Ich würde daher vorschlagen einen ekligen media querry für eine gering aufgelöste Ansicht zu erstellen und sonst die fonts an vw oder vh anzupassen.

**Comment by qwrtzp** [comment]
Die Darstellung bei der 320 x 480 Auflösung finde ich es eigentlich in Ordnung, weil die Bilder dann den ganzen Bildschirm ausfüllen und man dann eben durch die durch swiped. Ist fast so als wäre es für mobile angepasst. Die mittleren Größen (Netbooks, Tablets) finde ich eher hässlich, weil man da ja eher eine Desktop-artige Liste erwartet.

**Comment by qwrtzp** [comment]
Sieht jetzt schicker aus! Bei manchen Auflösungen hat man jetzt noch folgenden Effekt. 

![](http://i.imgur.com/GdWoypR.png)

Da würde ich eher erwarten, das das Bild nicht versucht möglichst groß zu sein, sondern die gleiche Größe wie die anderen hat. Weiß natürlich nicht wie machbar das ist.

**Comment by CDanU** [comment]
Um die Bilder gleich groß zu halten und das flex-grow zu behalten ist so wie ich raus gefunden haben nur möglich wen die Anzahl der Elemente in einer Reihe fest gesetzt wird. Damit kann man dann ein eher scheußliches und fragiles Konstrukt über media querrys erstellen (siehe die grünen Kästen hier: [~link~](https://www.aaron-gustafson.com/speaking-engagements/) ). 

Wen man flex-grow entfernt sind alle Bilder zwar gleich groß, jedoch entstehen  links und oder rechts Ränder die rel. groß werden können.

Letztendlich wäre mein Vorschlag folgender:

.showcase .card-book {
  width: **260px**;
  max-width: **300px**;
...
}

Damit sieht das im Schlimmsten falle so aus:

![screenshot_20160108_135951](https://cloud.githubusercontent.com/assets/15148226/12198480/af285d86-b610-11e5-9854-be3473f9be2d.png)

**Comment by DSIW** [comment]
Die Anzahl der Elemente in einer Reihe können wir nicht festlegen. In der mobilen Ansicht sollte es nur ein Buch sein, wobei es in der Desktop-Variante mehrere Bücher sein können. 

Welche Ränder meinst du? Ich kann keine feststellen.

Damit das letzte Buch links erscheint:
```css
.flex-container { 
    justify-content: flex-start;
}
```

**Comment by CDanU** [comment]
Rechts die weiße Fläche meine ich:
![screenshot_20160108_142105](https://cloud.githubusercontent.com/assets/15148226/12198737/fc11a29a-b612-11e5-9c8e-f3c92d8fa7ac.png)

**Comment by CDanU** [comment]
Da alle Vorschläge suboptimal waren habe ich den das ganze letztendlich mit den media querrys umgesetzt da diese die beste Lösung bieten.
