### ISSUE TITLE
Error beim Annehmen eines Änderungsantrag (wenn kein Pseudonym vergeben)

### ISSUE THREAD

**Issue by qwrtzp** [DSIW/sdf#101]
Will man als Admin den Änderungsantrag eines Users annehmen, der kein Pseudonym vergeben hat, kommt es zu einem Fehler, weil versucht wird das Pseudoym zu setzen (vermutlich auf **""**)

```
IntegrityError at /accounts/9/change_user_profile_accept/

UNIQUE constraint failed: auth_user.username

change_user_profile(request, change_user_data_id, True)
```

branch: feature/username

**Comment by localh0rzd** [comment]
Zusätzlich scheinen irgendwo auf dem Weg die Metadaten verloren gegangen zu sein (Feld heißt username, Fehlertext ist default).

**Comment by ottmann** [comment]
In Änderungsantrag oder bei der Reigstrierung?

**Comment by localh0rzd** [comment]
Beim Öffnen der Seite zum Ändern der Profildaten - Feld wird auch gleich als nicht valide markiert.

**Comment by ottmann** [comment]
ich kümmer mich darum. Danke für den Hinweis!
