### ISSUE TITLE
Profil-Bild und Ort nicht änderbar

### ISSUE THREAD

**Issue by DSIW** [DSIW/sdf#102]
Nach den Änderungen, die den Antrag der Accountänderungen betreffen, kann nun kein Profilbild hochgeladen werden, da das entsprechende Formularfeld fehlt. Außerdem sollte auch der Ort des Nutzers hier angegeben werden können. Der Ort sollte auch im Registrierungs-Formular angegeben werden können.

**Comment by ottmann** [comment]
Der Ort ist doch drin oder? Hatte das extra mich eingebaut.

Für das Profilbild hab ich bereits ein Issue geöffnet: #96

**Comment by DSIW** [comment]
Habe ich auch gerade gesehen, dass du das Issue geöffnet hast. :-) Was den Ort betrifft, hast du Recht und ich war blind. Sorry!
