### ISSUE TITLE
Buch aus gesperrtem Schaufenster besuch- und kaufbar

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#106]
Reproduktion:

- Buch aus dem Schaufenster eines Nutzers besuchen (um die id zu kennen)
- Schaufenster sperren

Zustand:

- Schaufenster gesperrt, wie es sein soll
- Bücher aus dem Schaufenster weiterhin abruf- und kaufbar

Erwartet:

- Schaufenster gesperrt, Bücher aus diesem Schaufenster sind für alle anderen als den Inhalber für die Dauer der Sperrung nicht mehr abrufbar.

**Comment by DSIW** [comment]
Wenn ein Schaufenster gesperrt wird, sollen die Bücher, die sich im Bezahlprozess befinden, abgebrochen werden?

**Comment by DSIW** [comment]
Marie, ich habe übersehen, dass du dich schon zugewiesen hast. Hab's aber grad schon gemacht.

**Comment by qwrtzp** [comment]
Kein Problem :+1:
