### ISSUE TITLE
Hochgeladenes Bild im Formular entfernen

### ISSUE THREAD

**Issue by DSIW** [DSIW/sdf#107]
Am besten wäre ein "X" im Formular. Dadurch müsste ein Hidden-Field mit dem Namen wie zB `delete_profile_image` gesetzt werden. Alternativ kann auch der Name des hochgeladenen Bildes auf empty geprüft werden. Dadurch wird das Bild vom Server gelöscht und die DB entsprechend aktualisiert. Anschließend muss das Standard-Bild angezeigt werden, was jetzt schon der Fall sein sollte.

Betrifft Bücher und Profil.

**Comment by localh0rzd** [comment]
Ist es so gewollt, dass das aktuell gesetzte Bild nicht mehr im Formular auftaucht (war ja früher der Fall)?

**Comment by localh0rzd** [comment]
Siehe #117.

**Comment by DSIW** [comment]
Oh ne, das aktuell gesetzte Bild sollte auch im Formular angezeigt werden.
