### ISSUE TITLE
Der Datepicker öffnet sich nicht beim Klicken auf das Label der Inputbox

### ISSUE THREAD

**Issue by qwrtzp** [DSIW/sdf#108]
Bezieht sich auf das Erstellen von Büchern.

**Comment by DSIW** [comment]
Das bezieht sich auch auf alle anderen Labels in diesem Formular. Ich hatte das Problem schon mal und habe es mit z-indexen gelöst. Das funktioniert nun nicht mehr. Der Einfachheit halber würde ich es per JS lösen: Der Nutzer klickt auf das Label und click damit aber das dahinter befindliche Input field. Das wäre doch OK, oder?

**Comment by CDanU** [comment]
Das mit dem z-index finde ich ist die bessere Lösung.  Es sollte eigentl. funktionieren wen du dem input Feld auch ein z-index gibst mit position: relative;

**Comment by DSIW** [comment]
Stimmt mit dem z-index auf dem Input-Field und dem `position: relative` geht es. Wieso braucht man das relative noch?
