### ISSUE TITLE
Benutzer können ihre eigenen Bücher kaufen

### ISSUE THREAD

**Issue by qwrtzp** [DSIW/sdf#109]
Die URL für einen neuen Preisvorschlag kann vom Besitzer des Buches aufgerufen werden (`offers/10/new_counteroffer`), was dazu führt dass man dann mit sich selbst handelt.

Es ist zu prüfen, auf welchen Wegen das sonst noch möglich ist.

**Comment by DSIW** [comment]
Habe wohl nur den Button ausgeblendet. Danke!

**Comment by localh0rzd** [comment]
Hab eine mögliche Lösung in issue/#103 umgesetzt, kann aber nicht abschätzen ob das bereits ausreicht - bitte anschauen. :3

**Comment by pynkpanther** [comment]
Wenn jemand auf Umwegen, also mehr als nur willentlich und auf keinen fall
aus versehen, unbedingt sein eigenes Buch kaufen möchte, kann uns das doch
eig egal sein oder?! Besonders wenn wir in einer Ausbaustufe an den
Transaktionen verdienen würden (z.b. 10 cent)
Am 08.01.2016 00:31 schrieb "Andrej" <notifications@github.com>:

**Comment by qwrtzp** [comment]
Kann man dann auch Bewertungen abgeben für den Kauf? Das wäre dann auf jeden Fall ein Problem.

**Comment by pynkpanther** [comment]
Stimmt, das wäre dann dich ein Problem
Am 08.01.2016 09:29 schrieb "qwrtzp" <notifications@github.com>:
