### ISSUE TITLE
Pseudonym kann verändert werden

### ISSUE THREAD

**Issue by DSIW** [DSIW/sdf#114]
Im Profil-Formular, ist das Feld nicht deaktiviert, obwohl schon ein Pseudonym gesetzt ist. Außerdem ist das Label "Username" und nicht "Pseudonym (optional)".

**Comment by ottmann** [comment]
Übernehme ich in meinem Feature Branch zum Pseudonym.
Wird morgen bearbeitet.

Welches Formular meinst du mit Profil Formular?

**Comment by DSIW** [comment]
Das Änderungs-Antrag-Formular unter `/accounts/:id/edit/`

**Comment by ottmann** [comment]
Also, dass das Feld angezeigt wird wenn ein Pseudonym gesetzt ist, ist korrekt.
Das wird so in den Anforderungen verlangt.

**Comment by DSIW** [comment]
Dass das Pseudonym verändert werden kann, steht so in den Anforderungen. Wieso habe ich das Gegenteilige dann implementiert?!

Also muss nur noch das Label geändert werden.

**Comment by ottmann** [comment]
:-D ich weis es nicht, aber mir ging es genauso wie dir :-)

**Comment by ottmann** [comment]
Ah mir ist gerade was eingefallen:
In den ersten Anforderungen stand drin, dass das Pseudonym ein mal vergeben werden kann.
Als dann in den Anforderung das mit dem Änderungsantrag dazu kamm, wurde bei den zu änderten Werten auch das Pseudonym aufgezählt. Daher vllt. die Verwirrung.

Das mit dem Ändern vom Pseudonym klappt auf jeden fall.
