### ISSUE TITLE
Login-Redirect funktioniert nicht

### ISSUE THREAD

**Issue by DSIW** [DSIW/sdf#115]
Der URL-Parameter `next` wird nicht berücksichtigt. Standardmäßig soll nach dem Login auf `/archive` weitergeleitet werden.

**Comment by CDanU** [comment]
Ich kann das nicht reproduzieren. Nach dem login werde ich auf die Archiv Seite weitergeleitet.

**Comment by DSIW** [comment]
Wenn die URL `/login/?next=/offers/12/start_payment/` lautet, wird immer noch auf das Archiv weitergeleitet und nicht auf `/offers/12/start_payment/`.
