### ISSUE TITLE
Verlinkung des Buchcovers

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#116]
Meiner Meinung nach ist es etwas unbequem, wenn man auch beim Klick auf das Buchcover die Details aufgeklappt bekommt, welche es auch über die drei Punkte unten gibt. Stattdessen sollte das Cover direkt auf die Detailseite verweisen.

Was meint ihr dazu?

**Comment by DSIW** [comment]
Ja, das hatte ich auch noch vor zu ändern. Sonst sind es zu viele Klicks. Ggf. könnte man den Titel auch direkt zum Buch verlinken.
