### ISSUE TITLE
Graue Hervorhebung springt beim Anlegen eines Buchs von "Archiv" auf "Alle Bücher"

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#119]
Ist nur eine Kleinigkeit, wirkt auf mich trotzdem etwas inkonsistent.

**Comment by DSIW** [comment]
Ja, das ist mir auch shcon aufgefallen. Liegt daran, dass ich die Hervorhebung mit JS mache, und den aktuellen Pfad prüfe mit dem im href. Da "/books/:id" in "/books" vorkommt, wird das markiert. Sollte das Archiv markiert sein?

**Comment by localh0rzd** [comment]
Ok, ist ja auch nur eine Kleinigkeit. :3
