### ISSUE TITLE
Bezahlprozess in für Nutzer "kaputtem" Zustand, wenn man nach dem Bezahlen nicht dem Link auf die Händlerseite folgt

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#122]
Seitens Book2 bleibt der Bezahlprozess aktiv, wenn man zu PP geht gibt es folgende Meldung:

>[...] Rechnung bereits bezahlt [...]
Ihr Einkauf konnte nicht abgeschlossen werden
Es gibt ein Problem mit dem PayPal-Konto des Händlers. Versuchen Sie es bitte etwas später noch einmal.

Dazu die Frage: Wird das Sandkastengeld wieder gutgeschrieben, wenn man an dieser Stelle den Bezahlprozess abbricht und neu startet? Ansonsten etwas unglücklich, dass man als Nutzer noch aktiv auf einen Link für die Rückkehr zum Händler klicken (oder ggf. nur länger warten) muss.

**Comment by DSIW** [comment]
Eine Gutschrift wird von unserem System nicht unterstützt.

Eigentlich werden IPN-Objekte mit den Zahlungsdetails von Paypal an unseren Server unter `/paypal/ipn-api` gesandt. Dies passiert, wenn Paypal die Zahlungsdetails erhalten hat. Vielleicht gibt es dort noch einen Bug...
