### ISSUE TITLE
Fehlende Pagination & Footer wenn Seiteninhalt viel Höhe benötigt

### ISSUE THREAD

**Issue by CDanU** [DSIW/sdf#130]
Tritt vor allem bei 'Alle Bücher' auf.

MAX_ELEMENTS_PER_PAGE = 2, ok
MAX_ELEMENTS_PER_PAGE = 8, problem

problematisch:
* * *
Mobile Chrome (v43.0)
Mobile Firefox (v41, v43)

ok:
* * *
Desktop Browser
Mobile Chrome >= v44.0 soll wohl funktionieren

**Comment by DSIW** [comment]
Footer und Pagination werden angezeigt unter Chrome 47.0.2526.83 unter Android 6.0.0.

**Comment by Gilga** [comment]
Bei mir passt es auch. Ich seh hier alles vernüpftig. Chrome 44.0.2403.133, Android 4.1.2

**Comment by CDanU** [comment]
Folgendes ist mir gerade aufgefallen: es ist nicht so das es hier einfach nur ein overflow problem oder ähnliches ist sondern das die Browser ab einer bestimmten Anz. an Book Cards einfach aufhören weiter zu arbeiten. Das merkt man das ab und zu die letzte Reihe nicht gefüllt wird obwohl noch weitere Cards folgen müssten. Es ist kein CSS Problem sondern das wir irgend eine Grenze sprängen.
Entferne ich aus dem __book_card template das card-reveal div wird alles geladen. 

WTH. so etwas habe ich noch nie erlebt.

**Comment by Gilga** [comment]
Irgendeine Art von Speicherbegrenzung? Bei mir brauch er ja eh lange damit die Seite sich aufbaut, wegen bilder usw. Tja Mobile Geräte sind halt sehr begrenzt...

**Comment by DSIW** [comment]
Ich kann mir nicht vorstellen, dass das card-reveal mit viel Speicher zusammen hängt. Das sind ja nur ein paar divs und Text. Wir könnten aber das card-reveal in der mobilen Ansicht entfernen. Müssten dann serverseitig prüfen, ob der Request von einem mobilen Gerät kommt. Prüft man das anhand vom User-Agent?! Das ist anscheinend keine sehr zuverlässige Methode: https://stackoverflow.com/questions/3514784/what-is-the-best-way-to-detect-a-mobile-device-in-jquery?rq=1#comment10959034_3540295
