### ISSUE TITLE
Suchleiste nicht ganz optimal? (Mobile)

### ISSUE THREAD

**Issue by Gilga** [DSIW/sdf#133]
Als ich mit meinem Mobile auf Bücher Suche ging hatte ich mich etwas über das unglückliche Anordnen der Elemente in der Suchleiste gewundert. Soll das so belassen werden? (Chrome 44.0.2403.133, Android 4.1.2)

Screenshoot
http://postimg.org/image/wtiqgs007/

**Comment by DSIW** [comment]
Ist nicht optimal, aber würde ich so lassen. Eine Optimierung ist meiner Meinung nach zu aufwändig.

**Comment by qwrtzp** [comment]
Ich haette den Vorschlag die Sortierungs-Elemente fuer mobile in eine sidebar zu packen.

**Comment by qwrtzp** [comment]
Also die Idee scheint mir doch schwieriger zu sein weil wir ja schon so eine Sidebar haben.

**Comment by DSIW** [comment]
Wir könnten einen Dropdown anzeigen, der alle Möglichkeiten enthält und durch die Auswahl die Seite neugeladen wird (JS).

**Comment by qwrtzp** [comment]
Okay klingt gut, wäre aber zumindest für mich ein größerer Aufwand wegen JS.

**Comment by CDanU** [comment]
So besser ? 

![screenshot_20160112_174037](https://cloud.githubusercontent.com/assets/15148226/12269818/8b301b30-b953-11e5-9d45-a1ff5468e0b8.png)

**Comment by DSIW** [comment]
Na, so ist es am besten! Echt super!! :+1:

**Comment by ottmann** [comment]
Finde es auch gut :+1:

**Comment by qwrtzp** [comment]
:+1:
