### ISSUE TITLE
Paypal-Adresse nicht änderbar

### ISSUE THREAD

**Issue by DSIW** [DSIW/sdf#134]
Zu dem Antrag sollte die Paypal-Adresse auch dazu, oder?

**Comment by ottmann** [comment]
Finde ich einen berechtigten Punkt.
Wird jedoch in den Anforderungen nicht gefordert.
Wollen wir es dennoch mit aufnehmen?

**Comment by DSIW** [comment]
Da wir bspw. auch den Ort mit dabei haben und es sonst keine andere Möglichkeit gibt es zu ändern, packen wir es einfach zum Antrag hinzu.

**Comment by ottmann** [comment]
Ok erledige ich morgen vor unserem Treffen :+1:
