### ISSUE TITLE
Eigenständiges Aufrufen von /payments/:id/success erlaubt Buchklau

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#137]
Sobald auf PP weitergeleitet wurde, kann man eigenhändig die URL aufrufen (id durchprobieren ist bei aufsteigenden ids nicht das Problem) und bekommt das Buch ohne Zahlung.

Möglicherweise braucht man die success-URL nicht mehr (stattdessen Weiterleitung z.B. ins Archiv), da die Zahlungsbestätigung über Webhooks kommt - ansonsten wäre denkbar, die id auf UUID umzustellen.

**Comment by DSIW** [comment]
IPN muss nicht abgesichert werden, weil hier das IPN von uns bei PayPal verifiziert wird.
