### ISSUE TITLE
@login_required von /accounts/:id entfernen?

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#143]
Ohne eingeloggt zu sein, lässt sich alles bis auf Nutzerprofile und deren Bewertungen betrachten. Wäre es evtl. schlüssiger, wenn dies auch ohne Login möglich ist (zumal der "Zum Nutzer"-Knopf auch ohne Login über dem Schaufenster gezeigt wird)?

**Comment by DSIW** [comment]
Da keine weiteren Daten im Profil angezeigt werden, können das Profil und die Bewertungen ruhig auch für Gäste sichtbar sein.
