### ISSUE TITLE
Mehrere Preisvorschläge nacheinander abgebbar

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#145]
Die Vorschläge nach dem Ersten finden zwar keine Beachtung, jedoch erhält der Nutzer auch keine Fehlermeldung.

EDIT: Ich war etwas unaufmerksam. Die Vorschläge werden alle wie sie es sollten bearbeitet, aber ist es lt. Anforderungen vorgesehen, mehrere Vorschläge nacheinander abgeben zu können, ohne dass der Verkäufer erstmal ablehnt? Es ist auch möglich, mehrmals den selben Preis anzubieten.

**Comment by ottmann** [comment]
Das war ein Feature vom letzten Sitzung. BL56. Wurde von Klaus umgesetzt

**Comment by ottmann** [comment]
Sitzung=Sprint

**Comment by pynkpanther** [comment]
Jo. Zuletzt hieß es es sollen mehrere Vorschläge abgegeben werden können.
Der Verkäufer sollte auch für jeden Vorschlag eine notification bekommen.
Wird eine angenommen sollten alle anderen automatisch abgelehnt werden
Am 14.01.2016 01:45 schrieb "ottmann" <notifications@github.com>:

**Comment by DSIW** [comment]
Mit der Abgabe eines weiteren Vorschlags wird quasi der alte Vorschlag bearbeitet. Der Kunde muss bei einem Tippfehler nicht auf die ablehnung warten und es könnte damit schon zu spät sein, sondern kann mit seinem Angebot noch weiter runter gehen. Somit können sich die Nutzer erst mal gegenseitig unterbieten und wenn der Verkäufer einen Preisvorschlag annimmt, ist die "Auktion" beendet.

**Comment by DSIW** [comment]
Da dieses Verhalten Absicht ist, schließe ich das Issue
