### ISSUE TITLE
Name in Benachrichtigungen auf dem Server fälschlicherweise escaped

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#153]
Lokal konnte ich das Problem nicht nachstellen, auf dem Server wird in den Benachrichtigungen der Name aus full_name() escaped.

![](http://i.imgur.com/tTeD4ov.png)

**Comment by localh0rzd** [comment]
Habe ein NBSP als Zeichen eingesetzt.

**Comment by DSIW** [comment]
Komisch. Danke!
