### ISSUE TITLE
Benutzer kann sich ohne Email-Bestätigung anmelden

### ISSUE THREAD

**Issue by DSIW** [DSIW/sdf#16]
Erst nachdem der Nutzer auf den Link in der Registrierungs-Email geklickt hat und die E-Mail-Adresse bestätigt ist, kann sich dieser anmelden.

Im Moment kann man sich auch ohne Klick auf den Link anmelden.

Abfrage von `user.emailConfirm` und Anzeige einer Message, wie "Sie müssen erst Ihre E-Mail-Adresse validieren, indem Sie in der E-Mail auf den Bestätigungslink klicken." Vielleicht ist ein Link zu "Bestätigungsemail nicht erhalten" notwendig, wodurch nochmals eine Email geschickt werden kann?

**Comment by ottmann** [comment]
Dieser Punkt wird nun durch das BL Item 42 abgedeckt. Die Anmerkung hab ich ins Trello mit übernommen.
