### ISSUE TITLE
Image Upload bei User Update funktioniert nicht

### ISSUE THREAD

**Issue by ottmann** [DSIW/sdf#23]

**Comment by localh0rzd** [comment]
Das Problem tritt auf, da zwei mal auf request.POST zugegriffen wird (vgl. https://github.com/tomchristie/django-rest-framework/issues/2774). Wenn man die Middlewareklasse ``app.middleware.http_method_middleware.HttpMethodMiddleware` auskommentiert, funktioniert das Hochladen. Ein erneutes Absenden des selben Formulars meckert auch bzgl. falschem CSRF-Token. Wird die selbstgebaute Middlewareklasse zwingend benötigt und was genau macht sie (zusätzlich)?

**Comment by ottmann** [comment]
Danke für das Feedback! Werde ich mir morgen genauer anschauen.
