### ISSUE TITLE
Buch_erstellen_und_gleichzeitig_veröffentlichen_Exception

### ISSUE THREAD

**Issue by pynkpanther** [DSIW/sdf#24]
- Buch erstellen:
  - wenn man gleich verkaufen auswählt wird beim klicken auf "speichern" eine exception geworfen
  - Buch wird erstellt aber nicht veröffentlicht

**Comment by CDanU** [comment]
Der Fehler entstand durch eine unvollständige Umbenennung von book_id auf id beim mergen. Ich gehe noch fix alles durch und pushe den fix.
