### ISSUE TITLE
manage.py createsuperuser - exception bei email-abrfrage

### ISSUE THREAD

**Issue by pynkpanther** [DSIW/sdf#25]
- Admin-login verlangt email
  - python manage.py createsuperuser wirft exception 'django.core.exceptions.FieldDoesNotExist: User has no field named''   <--- das sind zwei hochkommatas

**Comment by DSIW** [comment]
Nicht dringend, da durch `reset_db.sh` und den Seed-Daten auch ein Admin angelegt wird.
