### ISSUE TITLE
Schaufester innerhalb des Schaufensters sperren

### ISSUE THREAD

**Issue by jrosenfeld** [DSIW/sdf#29]
Ich hab gerade das mergen meines showcaseDisable-Branches durchgeführt. Dabei ist mir aufgefallen, dass ich das sperren durch den Admin lediglich über die Adminseite eingebaut habe. 

Nun frage ich mich, ob ich noch ein Knopf in die Schaufenster-Ansicht für den Admin hätte einbauen sollen. Ist das erwünscht?

**Comment by DSIW** [comment]
Ein Knopf für den Moderator wäre hier bestimmt nicht schlecht. Werden wohl den Moderator nur auf unserer Anwendung Zugriff erlauben, sodass er /admin gar nicht nutzt. Hier hätte dann eben nur der wirkliche Admin Zugriff.

Wenn es wirklich nur ein Knopf ist mit einer Anfrage, kannst du das gerne direkt in `develop` commiten. Ein Feature-Branch lohnt sich dafür nicht.
