### ISSUE TITLE
TODO: Begrenzung der Bildgrößen (Profilbild, Schaufensterbild) hinsichtlich Abmessungen und Dateigröße

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#30]

**Comment by ottmann** [comment]
https://djangosnippets.org/snippets/1966/

**Comment by ottmann** [comment]
Größe würde auch über einen Validator gehen:

```
from django.core.exceptions import ValidationError

class Product(models.Model):
    def validate_image(fieldfile_obj):
        filesize = fieldfile_obj.file.size
        megabyte_limit = 5.0
        if filesize > megabyte_limit*1024*1024:
            raise ValidationError("Max file size is %sMB" % str(megabyte_limit))

    image = models.ImageField(upload_to="/a/b/c/", validators=[validate_image])
```

**Comment by localh0rzd** [comment]
Danke für die Vorlage. Ich habe jetzt eine Dateigrößenprüfung eingebaut. Zusätzlich wird im Formular das bereits vorhandene Cover dargestellt, wenn der Upload erfolglos war.

Die Prüfung der Bildgröße habe ich erstmal weggelassen, da im aktuellen Design auch übergroße Bilder das Layout nicht zerstören.
