### ISSUE TITLE
Anmelden trotz Nicht-Bestätigung der Email

### ISSUE THREAD

**Issue by Gilga** [DSIW/sdf#31]
Mir ist aufgefallen, dass ich mich anmelden konnte, obwohl ich meine Email Adresse nicht bestätigt habe. Soll das so sein?

Desweiteren ist mir aufgefallen, dass bei "sendConfirmEmail" das "Senden" der Email Bestätigung nicht in der letzten Zeile der Funktion steht. Wenn ein Fehler mit der DB auftritt wird die Email zwar verschickt, aber es extiert kein Eintrag zu dem Link. (z.B. wenn DB blockiert ist). Es wär daher besser, wenn das Senden am Ende steht, damit es erst garnicht zum Senden kommt, wenn ein DB Fehler eintritt. (Generell müsste man eigtl. MailServer und DBServer Connection vorher testen.)
Ich hatte ein ähnliches Problem mit Password Reset.

**Comment by localh0rzd** [comment]
Zu Punkt 1: Habe ich bereits in Pullrequest #28 geändert.
Zur Reihenfolge beim Senden: Eben geändert.

Im Produktivbetrieb sollten wir sowieso darüber nachdenken auf MySQL umzusteigen, um Probleme bei der Verfügbarkeit zu vermeiden.
