### ISSUE TITLE
Admin-Login funktioniert nur manchmal

### ISSUE THREAD

**Issue by DSIW** [DSIW/sdf#46]
Bei Aufruf von http://sdf.localhost/admin/login/ wird eine Exception angezeigt, wenn kein Nutzer  angemeldet war. Wenn man sich als max angemeldet hat, funktioniert auch die Admin-Login-Seite.
Im Branch `feature/paypal` funktioniert es anscheinend.

```
AttributeError: 'NoneType' object has no attribute 'is_active'
```

**Comment by pynkpanther** [comment]
lokal und auf htw server gerade nochmal getestet, kann geschlossen werden. wenn niemand was einzuwenden hat schließ ich das heute abend
