### ISSUE TITLE
Buchbilder: Neu angelegtes Buch (mit Bild) überschreibt Buchbild anderer Bücher. 

### ISSUE THREAD

**Issue by CDanU** [DSIW/sdf#51]
Bücher die im Archiv mittels 'Buch anlegen' erstellt werden (sowohl mit Verkaufsangebot als auch ohne), überschreiben Buchbilder aller anderen Bücher (inklusive Bücher anderer Nutzer) die auch mittels 'Buch anlegen' erstellt wurden.
Wurde das Buchbild über 'Bearbeiten' gewechselt bleiben dieses selbst nach einem erneuten 'Buch anlegen' erhalten.

Im image Verzeichniss liegt eine book_None.jpg, diese Datei wird wohl beim 'Buch anlegen' erzeugt und überschrieben.

**Comment by qwrtzp** [comment]
In models.py, book_directory_path wird der Name aus der Id des Buches generiert.
```
upload_dir_path = 'images/books/book_{0}.{1}'.format(instance.id, ext)
```
Ich nehme an zum Zeitpunkt des Erstellens des Buches hat die Instanz noch keine id, daher ist bei allen Büchern, bei denen ein Bild beim Erstellen hochgeladen wird vermerkt, dass ihr Bild book_None heißt.
