### ISSUE TITLE
User Standartbild

### ISSUE THREAD

**Issue by CDanU** [DSIW/sdf#53]
Es wäre schön wen ein User der kein Profilbild gesetzt hat ein Standartbild zugewiesen bekommt. Dies ist vor allem für die SchaufensterOverview nützlich.

**Comment by DSIW** [comment]
Ich habe im `feature/user-detail` ein Standard-Bild mit drin. Das könnte man nutzen. Wenn du magst, kann du den einen Commit gerne bei dir in deinen Feature-Branch cherry-picken.
