### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by Gilga** [DSIW/sdf#54]
Da der Build nicht mehr klappt (weder bei CodeShip, noch bei mir), habe ich mich den Problem angenommen. In der requirements.txt ist Pillow der Verursacher der Probleme. Dazu habe ich folgendes gefunden:

"libjpeg-dev is required to be able to process jpegs with pillow (or PIL), so you need to install it and then recompile pillow. It also seems that libjpeg8-dev is needed on Ubuntu 14.04"
(http://stackoverflow.com/questions/8915296/python-image-library-fails-with-message-decoder-jpeg-not-available-pil)

Demnach muss man in der Console eingeben:
sudo apt-get install libjpeg-dev

Jetzt sollte der Build wieder klappen.

Noch was: Das Invoke Package wirft beim compiling einen Syntax Error, jedoch wird es erfolgreich installiert??? Etwas seltsam...

Ich werde gleich die neue prepare_ubuntu.sh hochladen. Bei der prepare.sh weiß ich nicht genau ob hier dasselbe Problem auftritt wie bei Ubuntu.

**Comment by DSIW** [comment]
Auf jeden Fall ein guter Hinweis! Danke! Meinst du, dass das auch was mit watson zu tun hat?

**Comment by Gilga** [comment]
Gute Frage, auf jedenfall klappt jetzt build :D

**Comment by DSIW** [comment]
Bei dir lokal? Bei Codeship ja anscheinend nicht...

**Comment by Gilga** [comment]
Also ich bin nicht schuld. Nachdem paypal gemerged wurde ging garnichts mehr. Ich hatte den old develop mit meiner kleinen Änderung noch da und hab den hochgeladen. Dieser geht.

**Comment by DSIW** [comment]
Durch die Versionsangabe von watson in der requirements.txt läuft der Build unter develop wieder durch.
