### ISSUE TITLE
Validierung der ISBN findet nicht statt (Maximallänge etc)

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#63]

**Comment by qwrtzp** [comment]
Wünschen wir eine richtige Validierung oder reicht das Überprüfen der Länge?

**Comment by DSIW** [comment]
Max-Länge ist zwingend erforderlich.

Regex für ISBN-Struktur kannst du ja mal ausprobieren. Wenn es nicht zu viel Aufwand ist:
* https://stackoverflow.com/questions/4381514/regular-expression-for-an-isbn-13
* http://howtodoinjava.com/2014/11/17/java-regex-validate-international-standard-book-number-isbns/

**Comment by pynkpanther** [comment]
ich würde aber sagen leer muss auch gehen. wegen usablity. Vermutlich haben
viel zu viele User gar kein Bock das einzutragen, bzw. wissen nicht wo man
schnell danach suchen kann. Ich hätte erhlich gesagt auch kein Bock.

2015-12-17 16:14 GMT+01:00 Max <notifications@github.com>:

**Comment by qwrtzp** [comment]
Implemented in [1575c58](https://github.com/DSIW/sdf/commit/1575c583abaaee1d855718d6dfdcb594083482ce)
