### ISSUE TITLE
Zu lange Büchernamen/Autor führen zu hässlicher Darstellung von Bücherkarten

### ISSUE THREAD

**Issue by qwrtzp** [DSIW/sdf#64]
**IST** Bei der Darstellung der Bücher als Karten (showcase etc) führen zu langer Titel/Autor zum "Überlauf" von Elementen, es kommt zu Überdeckung oder Sachen wie Preis werden wegen der Verschiebung gar nicht mehr angezeigt.

**SOLL** Entweder werden längere Namen bei der Darstellung abgekürzt *Ein Buchname der lan(...)* oder das Design der Karten angepasst, dass es dann irgendwie trotzdem sinnvoll angezeigt wird (kleiner font, dynamische Größe?). 
Begrenzung der Länge von Titel und Autor ist hier nicht sinnvoll, da der Effekt bei durchaus normalen, realen Titellängen eintritt.

**Comment by CDanU** [comment]
Ich habe gerade im issues/#64 branch ein wenig js-Code geschrieben der Schrittweise die font-size des Textes verringert bis der Text von der höhe passt.  Was noch problematisch ist sind sehr_lange_zusammen_geschiebene_wörter. Man könnte dort bestimmt auch irgendwie mit js ran, aber so wirklich sinnvoll halte ich das nicht. Hat jemand dazu noch eine Idee ?
