### ISSUE TITLE
Verkäufersuche liefert bei drei und mehr Suchbegriffen ggf. zu viele Treffer

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#68]
Bei zwei Worten wird davon ausgegangen, dass Vor- und Nachname gesucht sind. Bei mehr Worten ergeben sich ggf. Kombinationen, die nicht gefunden werden sollten, da die eingegebenen Begriffe beliebig und Vor- und Nachnamen vorkommen dürfen.

Diese Verhaltensweise ist hauptsächlich gedacht, um exotische Namen mit Leerzeichen abdecken zu können.

**Comment by DSIW** [comment]
Da es kein Problem im eigentlichen Sinn ist, schließe ich hier das Issue.
