### ISSUE TITLE
Exception beim Versenden von Buch (Sofortkauf)

### ISSUE THREAD

**Issue by DSIW** [DSIW/sdf#69]
Ein Buch wurde per Sofortkauf gekauft. Dadurch erscheint eine Benachrichtigung beim Verkäufer, dass er das Buch versenden kann. Durch einen Klick auf "Versenden" erscheint die Exception:

```
File ".../app_notification/models.py", line 131, in send_book
    counteroffer = get_object_or_404(Counteroffer, id=notification.counter_offer.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

`counter_offer` ist scheinbar nicht gesetzt, weil es ja kein Gegenangebot gibt.

**Comment by pynkpanther** [comment]
Kann ich mich drum kümmern.  Leider erst am Wochenende. Hab aba gerade mal
in den code geschaut. Sowie ich das sehe kann man die Zeile einfach
löschen. Das counteroffer Objekt wird in der Methode nichmal  benutzt

Ein Buch wurde per Sofortkauf gekauft. Dadurch erscheint eine
Benachrichtigung beim Verkäufer, dass er das Buch versenden kann. Durch
einen Klick auf "Versenden" erscheint die Exception:

File ".../app_notification/models.py", line 131, in send_book
    counteroffer = get_object_or_404(Counteroffer,
id=notification.counter_offer.id)
AttributeError: 'NoneType' object has no attribute 'id'

counter_offer ist scheinbar nicht gesetzt, weil es ja kein Gegenangebot
gibt.

—
Reply to this email directly or view it on GitHub
<https://github.com/DSIW/sdf/issues/69>.

**Comment by DSIW** [comment]
Meinst du die Zeile? https://github.com/DSIW/sdf/blob/develop/app_notification/models.py#L131
Das Objekt wird doch genutzt?!

**Comment by pynkpanther** [comment]
ach tatsächlich, habs in der eile aufm handy übersehen. ich mach das am We.

2015-12-17 14:11 GMT+01:00 Max <notifications@github.com>:
