### ISSUE TITLE
Admin-Seite auf Server prüfen

### ISSUE THREAD

**Issue by DSIW** [DSIW/sdf#74]

**Comment by DSIW** [comment]
CSS nicht geladen, weil 404 bei `static/admin/css/*.css`

**Comment by DSIW** [comment]
Wir brauchen nun eigentlich die Admin-Oberfläche gar nicht mehr, da das Schaufenster innerhalb unserer Oberfläche geändert werden kann. Auch die Anträge werden bei uns abgehandelt. Seht ihr das auch so?

**Comment by ottmann** [comment]
Der einzige Punkt der mir noch einfällt, was nur in der Admin Oberfläche geht ist, einen Nutzer als Mitarbeiter einzustufen. Werden wir vermutlich nicht zeigen aber könnte als Frage kommen. Finde aber, das geht auch ganz gut ohne CSS, sieht halt net schön aus.

**Comment by ottmann** [comment]
Wenn wir im static Ordner einfach einen Ordner admin/css anlegen und dort die beiden CSS Dateien ablegen, funktioniert es auch auf dem Server. Hab das gerade mal getestet. Wollen wir das machen?

**Comment by CDanU** [comment]
Wir haben doch sicherlich keinen MS Server am laufen, ein symlink müsste doch auch dafür funktionieren oder ? Selbst git würde sogar mit symlinks kein Problem haben.

**Comment by DSIW** [comment]
Weshalb brauchen wir einen MS Server?? Die Staff-Geschichte habe ich gerade mal zum Nutzer hinzugefügt. Dann brauchen wir die Admin-Oberfläche wirklich nicht mehr. Finde ich gut!
