### ISSUE TITLE
HTTP-Error bei Absenden des Buchformulars

### ISSUE THREAD

**Issue by DSIW** [DSIW/sdf#75]
Fehler: `HTTP-Error: 413 Entity too large`

Es muss geprüft werden, unter welchen Umständen dieser Fehler auftritt. Bei mir trat es bei Änderung eines Buches auf. Wahrscheinlich liegt es an dem angegebenen Bild.

**Comment by localh0rzd** [comment]
Ich habe eben lokal ein 10000x10000 Pixel großes Rausch-JPEG hochgeladen, wurde anstandslos gefressen; besagter Fehler ist bisher nicht aufgetaucht.

In diesem Zusammenhang noch die Frage: HTTP 412 ist "Precondition failed" - ist HTTP 413 gemeint und 412 ein Tippfehler?

**Comment by DSIW** [comment]
Habe es auf 413 geändert. Danke!

**Comment by pynkpanther** [comment]
auf dem server:
* 5.93 MB, 1920x1080   => 413
* 0.98 MB, 1920x1080   => funktioniert ,allerdings wird der verweiß auf bild "book_16.jpg", (ein HP-Lovecraft bild) gespeichert und angezeigt 
* 1,93 MB, 1920x1080   => 413

lokal:
* 5.93 MB, 1920x1080   => form wird wie gewollt validiert und maximalgröße von 5MB wird rot angezeigt
* 0.98 MB, 1920x1080   => funktioniert
* 1,93 MB, 1920x1080   => funktioniert

**Comment by pynkpanther** [comment]
das könnte die lösung sein:
https://laracasts.com/discuss/channels/forge/413-request-entity-too-large-nginx162

finde bei mir aber keine [nginx.conf], gibts die nur auf dem server?

**Comment by pynkpanther** [comment]
/etc/nginx/nginx.conf folgende zeile hinzugefügt:

client_max_body_size 100M;


Verhalten jetzt wie folgt:
* Bilder von 0 bis 5 MB werden anstandslos gefressen
* Bilder von 5 bis 100 MB werden mit roter Schrift (wie vorgesehen) angemerkelt
* Bilder von 100 bis unendlich MB geben wieder 413

wenn keiner was dagegen hat schließ ich den issue heute abend

**Comment by DSIW** [comment]
Habe die Zeile unter `server { ... }` auf dem Server hinzugefügt.
