### ISSUE TITLE
Buch an Käufer nach Preisvorschlag-Annahme durch Verkäufer

### ISSUE THREAD

**Issue by DSIW** [DSIW/sdf#78]
Bei Annahme des Preisvorschlags des Käufers geht das Buch direkt zum Käufer über. Ein Timeout ist hier nicht notwendig.

**Comment by pynkpanther** [comment]
Nein erst sobald bezahlt wurde (oder sogar erst nach Versand? Dann wäre es
egal ob sofortkauf oder preisvorschlag). bei Annahme des preisvorschlages
wird es erst markiert. Timeout ist trotzdem nicht notwendig, da Akzeptanz
des preis Vorschlages verbindlich ist
Am 17.12.2015 14:08 schrieb "Max" <notifications@github.com>:

**Comment by DSIW** [comment]
Bei Annahme wird das Buch aus dem Schaufenster entfernt und nicht nur ausgegraut und es gibt keinen Timeout.

**Comment by pynkpanther** [comment]
Also gibt es kein Szenario in dem das Buch ausgegraut wird? Steht aber
anders in den Anforderungen? Ham wir auch nicht so besprochen denke ich.
Wie wurde das jetzt beschlossen? Also Sinn macht es schon, nur wenn es
anders mit Alex besprochen war / in den Anforderungen steht, dann würd ichs
nicht ändern

**Comment by DSIW** [comment]
Das Buch wird während des Bezahlprozesses beim Sofortkauf ausgegraut. Habe das gerade mit Jens so besprochen, ich denke, dass das so passt?!

**Comment by pynkpanther** [comment]
"Wurde ein Buch bestellt, wird es im Schaufenster markiert (keine neuen
Bestellungen
möglich), und an den potenziellen Käufer wird eine Nachricht mit den
Bezahldaten
geschickt. Die Bezahlung geschieht über Paypal (für das Projekt soll die
Sandbox von
Paypal verwendet werden). Ist die Bezahlung erfolgt, verschickt der
Verkäufer das Buch
(in unserem Projekt: der Käufer erhält eine Nachricht "Ihr Buch xxx wurde
versandt ...").
Gleichzeitig wird das Buch aus Archiv und Schaufenster des Verkäufers
entfernt und
dem Archiv des Käufers hinzugefügt."..... So wie ich das lese wechselt ed
in jedem Fall es erst mit dem Versand das Archiv
Am 17.12.2015 20:32 schrieb "Max" <notifications@github.com>:

**Comment by ottmann** [comment]
Das Buch sollte auch erst nach dem Versand wechseln.
Da die Annahme vom Preisvorschlag jedoch bindend ist, ist es sinnvoll das Buch nicht mehr im Schaufenster anzuzeigen. Das "ausgrauen" ist ja deswegen, da der Sofortkauf nicht direkt bindend ist und es eine Möglichkeit gibt, dass das Buch wieder zum Verkauf steht.

Bis auf die Unterscheidung von dem Timeout und dem Zeitpunkt wann das Buch aus dem Schaufenster entfernt wird, wären die beiden Kaufprozess identisch. Müsste so doch eigentlich dann zu den Anforderungen und dem was wir mit Frau Alexander besprochen haben passen oder?

**Comment by pynkpanther** [comment]
ja so hört sich das gut an
