### ISSUE TITLE
Gesetztes Pseudonym-Feld wird beim Account bearbeiten geleert und das Formular ist nicht valide, da das Pseudonym bereits vergeben sein soll

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#80]
Schritte zur Reproduktion:

- Nutzer mit Pseudonym haben
- Accound bearbeiten
- Formular abschicken --> Fehler

**Comment by ottmann** [comment]
Da ich das Formular bei meinem BI eh anfassen muss, übernehme ich das Issue

**Comment by DSIW** [comment]
Das Problem besteht in `feature/B46-Startseite` nicht. Wenn es in develop gemerged ist, können wir es nochmals überprüfen.

**Comment by DSIW** [comment]
Der Branch ist nun gemerged. Ich habe nun ein anderes Problem: Dadurch, dass die Prüfung nach einem bereits existierenden Pseudonym eingebaut ist, kann das Formular nicht aktualisiert werden, weil das Pseudonym schon existiert. Beim Aktualisieren des Benutzers darf natürlich das bereits gesetzte Pseudonym weiterhin genutzt werden.

**Comment by localh0rzd** [comment]
Ich habe soeben den Fehler insofern beseitigt, als dass man mit bereits gesetztem Pseudonym keine Probleme mehr hat. Allerdings wird bei weiteren Eingabefehlern im Formular das Pseudonym-Feld weiterhin nicht neu bestückt, sondern bleibt leer.

**Comment by DSIW** [comment]
Welchen Browser nutzt du?

**Comment by localh0rzd** [comment]
Den aktuellsten Firefox.

**Comment by DSIW** [comment]
Im Chromium, als auch im FF bekomme ich beim Bearbeiten eines Profils die Meldung: "Account konnte nicht aktualisiert werden" und beim Feld "Das gewählte Pseudonym ist bereits vergeben."

**Comment by localh0rzd** [comment]
Tatsache, ich jetzt auch wieder - irgendwas habe ich wohl verkackt...

**Comment by DSIW** [comment]
Müsste hier https://github.com/DSIW/sdf/blob/develop/app_user/models.py#L14 nicht stehen: alle außer mir?

**Comment by localh0rzd** [comment]
Sozusagen, aber dort wird nur der im Formularfeld angegebene Feld übergeben - wüsste spontan nicht, wie ich dort auf den aktuellen Nutzer kommen könnte.

**Comment by DSIW** [comment]
Alternativ kannst du die `save()` überschreiben oder im Formular die `clean()` wie hier: https://github.com/DSIW/sdf/blob/develop/app_book/forms.py#L65

**Comment by localh0rzd** [comment]
Das Problem scheint zu sein, dass das Pseudonym des Formulars beim POST-Aufruf immer leer ist - das erklärt auch, warum es bei Fehleingaben leer dargestellt wird. Sehe allerdings gerade nicht durch, wo ```username``` "verloren geht".
http://i.imgur.com/XAQSua6.png

**Comment by DSIW** [comment]
Ich schätze durch das "disabled"-Attribut?

**Comment by localh0rzd** [comment]
In der Tat - nach dem Auskommentieren ist die Variable wieder gefüllt (löst zwar das Issue nicht, aber hilft schonmal etwas).

**Comment by DSIW** [comment]
Vllt muss man hier https://github.com/DSIW/sdf/blob/develop/app_user/forms.py#L88 `self.fields['username'] = self.instance.username` hinzufügen, damit das Formular den Wert aus der DB nimmt?

**Comment by localh0rzd** [comment]
Ne, das macht es kaputt, da dort FormField-Klassen drin sind.

**Comment by pynkpanther** [comment]
nehmen wir "profil bearbeiten" nicht eh raus, weil das nur auf antrag geschehen soll?

**Comment by localh0rzd** [comment]
Guter Punkt - in dem Fall könnte man eine Extraseite zum Setzen eines Pseudonyms machen, sofern noch keins gesetzt ist.

**Comment by DSIW** [comment]
Das ändert aber an dem Problem nichts, es befindet sich dann nur auf einer anderen Seite. Außerdem lassen wir am besten das Nutzer-Form so wie es ist, nur dass wir den Submit-Button in "Änderung beantragen" umbenennen, wenn gewisse Felder ausgefüllt sind, die das benötigen?! Wäre für den Nutzer am komfortabelsten...

**Comment by ottmann** [comment]
Ich hab mir das Ticket mal zugewiesen, da ich aktuell an dem Formular zur Änderung mit Alex zusammen dran bin. Plan ist es das aktuelle Nutzer-Bearbeiten Form, wie es Max erwähnt hat, abzuändern und damit eine Notification auszulösen. In dem Zusammenhang schau ich mir den Sachverhalt gleich noch mit an.
