### ISSUE TITLE
Standardbuchcover im Buch-anlegen-Formular fehlerhaft (ggf. nur im git fehlend?)

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#85]
![](http://i.imgur.com/Q6JyfrK.png)

**Comment by qwrtzp** [comment]
Yo, das Bild ist auf jeden Fall nicht im git, korrekt. Gibt es das denn noch bei irgendjemandem?

**Comment by ottmann** [comment]
Das Bild fehlt nur im git. Problem ist, dass als Pfad /media/ genutzt wird was durch die gitignore ausgeschlossen wird. Korrekt wäre es wenn das default Bild in /static/img liegt. Kann ich morgen oder Dienstag gern einbauen.
