### ISSUE TITLE
Skalierung des obersten Bilds auf der Startseite nicht optimal

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#88]
Bei zu kleiner Breite hat das Bild nicht genug "Puffer" in Richtung Höhe; evtl. lässt sich der Hintergrund auf zoomend statt skalierend umstellen?

![](http://i.imgur.com/i8qcXTS.png)

**Comment by DSIW** [comment]
@localh0rzd Jetzt müsste es gut aussehen. War doch einfacher, als gedacht. :+1:

**Comment by DSIW** [comment]
Leider wird es im Android-Browser nun hochkant gar nicht mehr angezeigt und quer sieht es hässlich aus.

**Comment by localh0rzd** [comment]
Es kommt noch erschwerend hinzu, dass sich die oberen Bedienelemente ineinanderschieben (war aber glaube ich vorher auch schon so)

![](http://i.imgur.com/ng6W16n.png)

**Comment by DSIW** [comment]
Wollen wir alle erdenklichen Auflösungen unterstützen? Können wir nicht eine Min-Auflösung voraussetzen? 480px ist echt wenig...

**Comment by localh0rzd** [comment]
Ich habe es einfach auf eine Größe gezogen, wie sie in etwa auf einem Telefon dargestellt würde - auf meinem Androiden habe ich das selbe Problem bei einer horizontalen auflösung von 1080 Pixeln (Hochformat).

**Comment by CDanU** [comment]
Ich habe mir das angesehen und auf Chrome ist das eine reinste Katastrophe wen man ein derartiges Hintergrundbild haben will. Das Hintergrundbild wird im Chrome nicht angezeigt bzw. unkenntlich verzerrt wen bei der css prop:  background: url(/static/img/book5.jpg) no-repeat bottom center;  die letzten zwei Parameter angegeben werden. Die komischen Sprünge werden definitiv durch den Hintergrund erzeugt. Ich habe ein paar Lösungsvorschläge die ich auf Stackoverflow gefunden habe wie .z.b. (link){http://fourkitchens.com/blog/article/fix-scrolling-performance-css-will-change-property} probiert und diese haben zwar generell bei einer etwas sinnvolleren Positionierung geholfen, jedoch aber nicht das eigentliche Problem gelöst. 

Ich versuche noch das Bild in einem tag zu laden, wen das dann aber auch keine ordentlichen Ergebnisse bringt würde letztendlich vorschlagen das Hintergrundbild zu entfernen.

**Comment by qwrtzp** [comment]
Welche Probleme bestehen jetzt noch? Ich kann bei Chrome und Firefox in den verschiedenen mobilen Varianten nichts hässliches mehr sehen.

**Comment by localh0rzd** [comment]
Die Bildgröße ändert sich beim Scrollen (wird breiter, wenn man wegscrollt), dadurch rückt die ganze Seite hin und her.

**Comment by localh0rzd** [comment]
https://cloud.mail.ru/public/Kr6j/Lti184qBM hier ein Video des Problems.

(Zusätzlich wäre noch anzumerken, dass manche Zufallszitate ziemlich lang werden und sich nach unten ausdehnen)

**Comment by localh0rzd** [comment]
Zusätzliches Problem: das Zwischenbild mit dem offenen polnischen Buch verschiebt sich unerwartet.

**Comment by DSIW** [comment]
Bei dir wird ja das Startbild angezeigt?! Wir können das Zwischenbild auch entfernen?

**Comment by CDanU** [comment]
Ich glaube das Hauptproblem liegt darin das Chrome die Adressleiste versteckt wen man runter scrollt und diese wieder anzeigt wen man hoch scrollt. Jedes mal wen die Sichtbarkeit der Adressleiste verändert wird berechnet der Browser die Höhe neu und es entstehen Sprünge in der Seite. Setzt man den Container des Bildes auf eine feste Größe besteht dieses Problem nicht mehr.

Kurz gesagt eine perfide Sabotageaktion der mobilen Browserhersteller, die wohl erzielen wollen das Seitendesign künftig nur noch mit JS vorgenommen wird kann.

**Comment by DSIW** [comment]
Da die Seite nun durch den Commit  0c88f16 nicht mehr ruckelt und auch das Hintergrundbild auf dem mobilen Browser angezeigt wird, schließe ich diesen Issue.
