### ISSUE TITLE
Kein Buchbild nach Korrektur eins form Fehlers

### ISSUE THREAD

**Issue by CDanU** [DSIW/sdf#90]
1: Beim Buch anlegen Daten + Bild eingeben, dabei jedoch einen Fehler machen (z.b. ISBN)
2: Absenden, 
3: Fehler korrigieren und nochmals absenden. Hier bei bleibt der Dateipfad für das Bild im input Feld erhalten.

Ergebnis: Angelegtes Buch hat das schniecke 'Missing Book Cover' Bild

Erwartung: Richtiges Bild oder zumindest eine Warnung beim Korrigieren des Formulares dass das Bild neu gesetzt werden muss.

**Comment by ottmann** [comment]
Hab eine Idee woran es liegt, schau es mir morgen an.
