### ISSUE TITLE
Kein Menü auf der Landing-Page wenn User angemeldet ist.

### ISSUE THREAD

**Issue by ottmann** [DSIW/sdf#92]
Ist ein User angemeldet und geht auf die Index (Landing Page) gibt es nur den Logout Button und weiter unten die Links zu den neuesten Schaufenstern und Angeboten. Würde es gut finden wenn hier auch das Menü, welches ansonsten vorhanden ist, dem Nutzer zur Verfügung steht. Ansonsten wird der Workflow kompliziert und nicht intuitiv.

**Comment by qwrtzp** [comment]
Sehen das die anderen auch so?

**Comment by DSIW** [comment]
Es sollte kein Link zur Landing-Page führen, wenn ich angemeldet bin. Stattdessen sollte das Archiv als angemeldete Landing-Page genutzt werden. Ich hatte die Buttons absichtlich nicht hinzugefügt, da diese auf mobilen Geräten nicht gut aussehen?!

**Comment by ottmann** [comment]
Dann müssten wir bei / und angemeldeten User einen Redirect machen. Find ich ne gute Lösung.

**Comment by DSIW** [comment]
Es könnte sein, dass bei einem erneuten Redirect zu Flash-Messages verloren gehen. Ich würde vorschlagen, dass wir alle Redirects auf die StartPage in den Views prüfen und ggf. ändern. Ist dann leider bissl aufwändiger...

**Comment by qwrtzp** [comment]
Tja, sehr passend. Ich habe gerade ein Menü eingebaut. Ist aber vielleicht nicht so schlimm. Wenn man da ist kriegt man eben ein Menü. Egal ob redirect oder nicht?

**Comment by qwrtzp** [comment]
btw gibt es auch schon die navigation wenn man auf der Startseite auf einem mobilen device ist

**Comment by ottmann** [comment]
Naja wenn du schon eins eingebaut hast können wir es ja auch deine Lösung nehmen :)

**Comment by qwrtzp** [comment]
Okay, dann schließe ich das hier.
