### ISSUE TITLE
Book²-Logo und Menüelemente, bzw. Buchcover und -beschreibung schieben sich ineinader und teilweise in eine 2. Zeile

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#93]
Sobald das Design auf "mobil" umspringt, ists wieder in Ordnung, allerdings passiert das zu spät.

![](http://i.imgur.com/M9Ku3D6.png)

![](http://i.imgur.com/MmrKWfL.png)

**Comment by CDanU** [comment]
Soweit ich das sehe ist ja 'nur' das obere Menü noch fehlerhaft und die Buchcover der Buch detailView, richtig ? 

Ich versuch erst mal die detailView zu fixen.

**Comment by qwrtzp** [comment]
Kann geschlossen werden, oder?

**Comment by CDanU** [comment]
Ja aber erst wen es dann auch wirklich drinnen ist.
