### ISSUE TITLE
"Öffentliche Bücher"-Zähler wird nicht dekrementiert

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#94]
Nach einem erfolgreichen Verkauf wird die Anzahl öffentlicher Bücher in der Profilansicht nicht weniger.

Wenn danach ein neues Buch veröffentlicht wird, wird die Anzahl inkrementiert (kein Rücksprung auf einen gültigen Wert).

**Comment by DSIW** [comment]
Das liegt wohl an den Offers, die nun nicht mehr gelöscht werden. Hier 
müsste man wohl nur noch die aktiven Offers berücksichtigen.

Gesendet mit AquaMail für Android
http://www.aqua-mail.com
