### ISSUE TITLE
Knöpfe auf Startseite fehlen in mobiler Variante

### ISSUE THREAD

**Issue by localh0rzd** [DSIW/sdf#99]
Weiterhin die in #88 beschriebenen Probleme.

**Comment by qwrtzp** [comment]
Die Buttons werden absichtlich ausgeblendet, es gibt nur dieses Ausklapp-Menü.

**Comment by localh0rzd** [comment]
Dann gibt es aber keine Möglichkeit mehr, sich einzuloggen - im ausklappbaren Menü wird nur "Alle Schaufenster" und "Alle Bücher" angeboten.

**Comment by qwrtzp** [comment]
Achso. Dann würde ich sagen das muss in das Ausklapp-Menü rein oder wir lassen nur den "Ausloggen" Button da. Finde ich auch sinnvoll.

**Comment by qwrtzp** [comment]
Habe jetzt keine Buttons hinzugefügt sondern Login/Register in das Ausklapp-Menü.
